### ISSUE TITLE
is it possible to select multiple area on images?

### ISSUE THREAD

**Issue by shamod** [odyniec/imgareaselect#12]
Can you please guide how to extend your tool on selecting multiple areas on a single image?

**Comment by odyniec** [comment]
Unfortunately not, that's not possible -- it's answered in the FAQ: http://odyniec.net/projects/imgareaselect/faq.html#faq-2. Extending the plugin to add this feature is also quite complicated, and definitely not something that could be explained in a few words.

However, this feature is requested frequently (that's why it made it to the FAQ) and I'm actually thinking of developing a separate plugin that can do multiple areas.

**Comment by jeremybmerrill** [comment]
Sorry to comment on a closed issue. but I didn't see a better place to put this.

I modified [imgAreaSelect](https://github.com/jazzido/tabula/blob/master/webapp/static/js/jquery.imgareaselect.js) to allow multi-select for [Tabula](https://github.com/jazzido/tabula). It's not quite in a releasable state, though it's in production in Tabula. 
- Most of the exposed options are supported, but not quite all (e.g. the semantics of cancelSelection on the API object are undefined with multiple selections -- should it clear all selections or just one?). 
- "Overlapping" selections are handled pretty well in the two-selection case, but fairly poorly in the three-selection case because the math is kind of hard.
- I'm not a JavaScript expert and I know nothing about testing JavaScript. So test coverage is untouched. 

I don't know if you're still planning on developing a fork for multiple selections. If so, I'd love to help out (and hopefully this would form a good basis for starting a collaborative version); if not, I'd love your feedback, if you'd be willing to give it, on how best to improve what I've got.

**Comment by odyniec** [comment]
@jeremybmerrill Sounds great! I'll definitely look into this, maybe not in the next few days as I'm quite busy with other stuff, but I added it to my long-term todo list so that it doesn't get lost. Is there any easily accessible demo of the multi-select feature that I could see?

**Comment by jeremybmerrill** [comment]
@odyniec Super. I totally understand about being busy -- I am too. Just wanted to note this someplace so that, eventually we can figure this out.

The best way to see this multi-select feature would be to download Tabula and "upload" a PDF to it. It's written in JRuby, so it's cross-platform, runs in the browser and doesn't need to be installed.

The easiest way to test is just to check out [this saved Tabula page](http://jeremybmerrill.com/demo/Tabula.html). It might be a bit buggy, since it's a saved page out of a web app and the endpoints it expects to exist don't actually exist. (But the imgareaselect mod should work reasonably normally.)

**Comment by nvijayasekar** [comment]
@jeremybmerrill I need your support for multiple area on image.I have seen your tabule image code which i tried but it doesnt work. I need your help for selecting multiple area on image.
You have modified imageareaselect code and accomplished that.Please suggest how to work on that .It would be good if i get that code .
Thanks ,Waiting for your reply.

**Comment by m8nli9ht** [comment]
@jeremybmerrill  thanks a lot for your good job !!!!

**Comment by VTSundar** [comment]
Please check this for multiple select in image


http://www.jqueryscript.net/other/jQuery-Plugin-For-Selecting-Multiple-Areas-of-An-Image-Select-Areas.html
